language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-25
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
script:
  - chmod +x gradlew
  - ./gradlew clean build

# Disable Travis container-based infrastructure to correct
# resource consumption in gradle presumably due to dexing.
sudo: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
