language: android
jdk: oraclejdk7
env:
  global:
    - ANDROID_TARGET=android-24
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
script:
  - chmod +x gradlew
  - ./gradlew clean build

# Disable Travis container-based infrastructure to correct
# resource consumption in gradle presumably due to dexing.
sudo: true